### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by Johndirr** [benfmiller/audalign#15]
Hi I wanted to try out audalign but had some trouble with the installation. The installation instructions in the readme wont let me install the module. I always get this error
```
pip install audalign
ERROR: Could not find a version that satisfies the requirement audalign (from versions: none)
ERROR: No matching distribution found for audalign
```

So I tried it with the following commands
`pip install git+https://github.com/benfmiller/audalign.git`
or (after downloading from github)
`pip install audalign-master.zip`

In both cases pip will state it "Successfully installed audalign-0.0.2" but it seams like the installation is not working. I just tried to import audalign and get:
`Traceback (most recent call last):
  File "aligndashit.py", line 1, in <module>
    import audalign
ModuleNotFoundError: No module named 'audalign'`

Also the Lib\site-packages\ of my python env have an audalign-0.0.2.dist-info folder but no audalign folder.

Any idea whats wrong?

EDIT: I'm on Windows10, Python 3.7.6

**Comment by benfmiller** [comment]
Hi! Sorry for the troubles. I fixed it up and it should work now.

I'm planning on uploading it to pypi soon, so "pip install audalign" should work by the end of the year.

pip install git+https://github.com/benfmiller/audalign.git
works for me now.

It was due to an error in setup.py, but now it should work.

**Comment by Johndirr** [comment]
No need to be sorry :)
Thank you. Installation works now.
