### ISSUE TITLE
No module named 'audalign.align'

### ISSUE THREAD

**Issue by pdarulewski** [benfmiller/audalign#28]
Hello there,

The newest version of the library `audalign==1.0.0` is giving me the following error while importing the module.

```
>>> import audalign

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pdaawr/Documents/project/metrics/venv.nosync/lib/python3.8/site-packages/audalign/__init__.py", line 21, in <module>
    import audalign.align.aligner as aligner
ModuleNotFoundError: No module named 'audalign.align'
```

There is no issue with the previous one, i.e 0.7.2. I tested both versions on python3.8

**Comment by benfmiller** [comment]
Thanks for letting me know! 
It turned out to be a problem with the `setup.py` file. A new version should be out by tonight.

**Comment by benfmiller** [comment]
v1.0.1 is out!

**Comment by pada-augmentedhearing** [comment]
Cool, it's working perfectly now :)

**Comment by pdarulewski** [comment]
Cool, it's working perfectly now :)
