### ISSUE TITLE
Update the dependencies

### ISSUE THREAD

**Issue by skinkie** [benfmiller/audalign#30]
At this moment many of the dependencies become unsupported. It would be nice that the package would use the latest versions of noisereduce, librosa, skikit, typed-ast, typing-extensions and others.

**Comment by benfmiller** [comment]
Sure! I can update the dependencies in the next couple of days. When I last tried to update the dependencies, several of them didn't support python 3.10. Hopefully they do now!

**Comment by skinkie** [comment]
> Sure! I can update the dependencies in the next couple of days. When I last tried to update the dependencies, several of them didn't support python 3.10. Hopefully they do now!

I am running it on 3.10 at this moment. The change below allowed me to run it on Gentoo. scikit-learn, numba and llvmlite where the biggest problems.

```diff
diff --git a/requirements.txt b/requirements.txt
index 7ad78a6..8a994b7 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -15,16 +15,14 @@ imageio==2.9.0
 iniconfig==1.1.1
 joblib==1.0.0
 kiwisolver==1.3.1
-librosa==0.8.0
-llvmlite==0.34.0
+librosa
 matplotlib==3.3.3
 mypy-extensions==0.4.3
 networkx==2.5
 noisereduce==1.1.0
 numpy==1.21.0
-numba==0.51.2
+numba
 packaging==20.8
-pathlib==1.0.1
 pathspec==0.8.1
 Pillow>=8.1.1
 pluggy==0.13.1
@@ -37,18 +35,18 @@ pytest==6.2.0
 pytest-xdist==2.2.1
 python-dateutil==2.8.1
 PyWavelets==1.1.1
-regex==2020.11.13
+regex
 requests==2.25.0
 resampy==0.2.2
-scikit-image>=0.17.2
-scikit-learn==0.23.2
-scipy==1.6.3
+scikit-image
+scikit-learn
+scipy
 six==1.15.0
 SoundFile==0.10.3.post1
 threadpoolctl==2.1.0
 tifffile==2020.12.8
 toml==0.10.2
 tqdm==4.54.1
-typed-ast==1.4.1
-typing-extensions==3.7.4.3
+typed-ast==1.5.3
+typing-extensions
 urllib3==1.26.5
```

**Comment by benfmiller** [comment]
Great! Would you be willing to put up a PR? I try to keep the versions explicit to prevent changes in dependencies from breaking integrations with other dependencies.

Otherwise, I can set it up tomorrow.

**Comment by skinkie** [comment]
> Great! Would you be willing to put up a PR? I try to keep the versions explicit to prevent changes in dependencies from breaking integrations with other dependencies.

Yes, I don't mind to do a PR, but I think you should check the noisereduce upgrade, which suggested that the API changed.

My goal of today was to investigate if I could do a PySide frontend for this, so I was already happy I ended up here ;)

**Comment by benfmiller** [comment]
Thanks! I'll take a look at it

That sounds neat! From the discussion in issue #24, I was planning on adding a Machine Learning based fingerprinting recognizer, then working on a flutter GUI, but I won't get to those for several months. PySide seems like a niftier frontend solution as well!

**Comment by forart** [comment]
Dunno if can help, but we collected some open source audio aligners in this page:
https://github.com/forart/HyMPS/blob/main/Aligners.md

Please check.

**Comment by benfmiller** [comment]
That's a pretty neat project!
Dependencies updated
