### ISSUE TITLE
Audio Alignment Gains

### ISSUE THREAD

**Issue by ronespu** [benfmiller/audalign#50]
Hello,

I've working whit your code; thank you very much is so useful.

My problem happens when I trying to reproduce the audio, the audio is amplified, therefore the noise floor as well. Is there a way to hold the original audios gains?

Thank you!

**Comment by benfmiller** [comment]
I'm glad it has been useful for you! Sorry for the late reply

Have you tried the `normalize` field in the `BaseConfig`?

```
import audalign as ad

fingerprint_rec = ad.FingerprintRecognizer()
fingerprint_rec.config.normalize = False
```
Then passing that to an align function?
