### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by forart** [benfmiller/audalign#52]
Hi there, we just realized that we've never asked for it: can you please "standardize" the license file ?

Although it may sounds like a minor aspect, a GH "uncompliant" license file causes an inconsistent generation of the relative badge:

![](https://flat.badgen.net/github/license/benfmiller/audalign/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/benfmiller/audalign/?label=LICENSE)

You can easily set a "correct" one through the GH's license wizard tool.

Last but not least, we're revising the [AUDIO category](https://github.com/forart/HyMPS#-) \ [Tools section](https://github.com/forart/HyMPS/blob/main/A_Tools.md#--) \ [Alignment/synch subsection](https://github.com/forart/HyMPS/blob/main/A_Tools.md#alignmentsynch-) where your project is listed, so let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by benfmiller** [comment]
Updated the license file so it now says MIT when I go to that link

I'm not sure what you could do to improve it, it already seems pretty neatly laid out

**Comment by forart** [comment]
Sorry for the late reply: it works now, thanks !
