### ISSUE TITLE
[Request] Modular installation of the package

### ISSUE THREAD

**Issue by mcosti** [benfmiller/audalign#56]
Hi! Once again, great work on this project!

Is there any chance that the requirements can be split into modular parts?

Like this:
```
pip install audalign[correlation,fingerprint]
```

At the moment the installation takes a very long time for parts of the code that I'm not using. For now, I simply extracted the correlation bits of code into my project in order to make it slimmer, but it could be great if this can be supported officially so I don't miss on any helpful updates from you.

Thank you

**Comment by benfmiller** [comment]
Sorry for the late reply

That's a good suggestion! The noisereduce dependency takes the vast majority of the time in my experience, and could easily be modularized.

I hadn't looked into this before, but I'll definitely add this. It would allow for adding new recognizers without increasing installation time, which is something I've wanted to do for a while

I'm glad you've found the project useful

**Comment by benfmiller** [comment]
Released in v1.3.0
