### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by WindowsNT** [benfmiller/audalign#57]
Failed building wheel for scikit-image

(Why do you need scikit-image anyway?)
I'm trying to use this promising library to audio align, but I can't install it.
What's the latest python version you tested with?

**Comment by benfmiller** [comment]
Scikit-image is only used in the visual-recognizer, so I was going to modularize it out per #56 

The current version of this package works with 3.9-3.11 on linux. Other dependencies didn't support 3.12 yet last time I checked.

What platform and python version are you running that's failing? Error messages?

**Comment by WindowsNT** [comment]
I was able to install by removing all versioning from requirements.txt. Windows 11 x64.

Now, since I already have the chromaprint voice for C++ and can take the fingerprint of audio, what would help is an explanation on what you do to find the alignment so I may be able to implement in C++ and avoid installing a python package.

Best.

**Comment by benfmiller** [comment]
Nice! I ought to add windows runs to the github actions

https://github.com/benfmiller/audalign/tree/main/audalign/recognizers/fingerprint contains all the fingerprinting code. The main process is:

1. Calclate peaks for audio spectrogram
2. Construct a string from combinations of the peaks and create a hash/fingerprint
3. Store each fingerprint and it's offset in the file in a hashmap
4. For lookup, count the number of hash matches between audio with the same offset. The most frequent offset is the most likely alignment

Hope that helps!
